@startuml create-sequence-diagram
!theme cerulean
' skinparam sequenceMessageAlign center

actor "Host" as host
participant "Whiteboared Server" as server
participant "Authentication Provider\n<Google | Microsoft | Apple>"
participant "Collaboard Server" as collaboard

== Initialization ==

host <--> server: wss://<domain>/<conferenceAlias>\n/<participantUuid>

== Authenticate with social provider ==

== User Authentication ==
host -> server: WSS
note right
{
  type: 'authenticate',
  provider: <collaboard | conceptboard>
  authProvider: <google | microsoft | apple>
  token: <token>
}
end note


== Finish process ==

server -> host: WSS
note right
{
  type: 'authenticated',
  whiteboardAuthToken: <token>
}
end note

@enduml